lcc.config = {
    scale = 1.3,
}

conky.config = {
    alignment = "middle_right",
    gap_x = T_.sr(50),
    gap_y = T_.sr(10),
    own_window_type = "normal",
}

-- Disable weather component (API broken / inaccurate)
lcc.panel = {
    "datetime",
    -- "weather",
    "system",
    "cpu",
    "memory",
    "storage",
    "network",
    { "vspace", -20 },
}
